version: "3"

services:
        www: &www
                image: ubuntu:20.04
                ports:
                        - "127.0.0.1:2001:22"
                        - "127.0.0.1:2021:80"
                working_dir: /app
                volumes:
                        - ./:/app
                entrypoint: ./pre_install.sh
        www1: 
                <<: *www
                ports:
                        - "127.0.0.1:2002:22"
                        - "127.0.0.1:2022:80"
        www2: 
                <<: *www
                ports:
                        - "127.0.0.1:2003:22"
                        - "127.0.0.1:2023:80"
        www3: 
                <<: *www
                ports:
                        - "127.0.0.1:2004:22"
                        - "127.0.0.1:2024:80"
        www4: 
                <<: *www
                ports:
                        - "127.0.0.1:2005:22"
                        - "127.0.0.1:2025:80"
        www5: 
                <<: *www
                ports:
                        - "127.0.0.1:2006:22"
                        - "127.0.0.1:2026:80"
        www6: 
                <<: *www
                ports:
                        - "127.0.0.1:2007:22"
                        - "127.0.0.1:2027:80"
        www7: 
                <<: *www
                ports:
                        - "127.0.0.1:2008:22"
                        - "127.0.0.1:2028:80"
        www8: 
                <<: *www
                ports:
                        - "127.0.0.1:2009:22"
                        - "127.0.0.1:2029:80"
        www9: 
                <<: *www
                ports:
                        - "127.0.0.1:2010:22"
                        - "127.0.0.1:2030:80"
